### ISSUE TITLE
add coreutils if going to later Ubuntu (20.4)

### ISSUE THREAD

**Issue by markhermeling** [f-squirrel/dockerized_cpp_build_example#3]
Thanks for the great content. Wanted to provide a heads-up that you need to add coreutils if you switch to Ubuntu 20.04 or nproc will not be available/

**Comment by f-squirrel** [comment]
Hi @markhermeling,
Thank you for the feedback, I am very glad to hear that you found my post useful!
To be honest, I see this repo is more an example of usage of the Makefile in a custom project than a reference to building Docker images. A potential user might use another distro, not always Debian-based, where all the `apt install` commands would be completely different (`yum` something). Thus, I do not see the point of adding any extra information, because the user will anyways have to search for distro-specific commands.
